name: zero_to_one
description: 

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.7

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  flutter_web_test: any
  test: ^1.6.3

dependency_overrides:
  flutter_web:
    path: ./flutter_web/packages/flutter_web
  flutter_web_test:
    path: ./flutter_web/packages/flutter_web_test
  flutter_web_ui:
    path: ./flutter_web/packages/flutter_web_ui

flutter:
  uses-material-design: true